[package]
name = "c4e5r"
version = "0.0.1"
edition = "2021"

[dependencies]
chess = "3.2"
timer = "0.2"
chrono = "0.4"
log = "0.4"
simple-logging = "2.0"
hashbrown = "0.13"

[profile.release]
strip = true
panic = "abort"

