[package]
name = "c4e5r"
version = "0.0.1"
edition = "2021"

[dependencies]
chess = "3.2.0"
timer = "0.2.0"
chrono = "0.4.23"
log = "0.4.17"
simple-logging = "2.0.2"

[profile.release]
strip = true
panic = "abort"

