// Time Management
pub const ESTIMATED_REST_MOVES: u16 = 40;
pub const EARLY_GAME_MAX_MOVES: u16 = 25;
pub const EARLY_GAME_MIN_REST_MOVES: u16 = 20;
pub const TIME_USAGE_PERCENT_DEFAULT: u16 = 90;
pub const TIME_USAGE_PERCENT_EARLY_GAME: u16 = 200;
