// Time Management
pub const ESTIMATED_REST_MOVES: u64 = 40;
pub const EARLY_GAME_MAX_MOVES: u64 = 25;
pub const EARLY_GAME_MIN_REST_MOVES: u64 = 20;
pub const TIME_USAGE_PERCENT_DEFAULT: u64 = 90;
pub const TIME_USAGE_PERCENT_EARLY_GAME: u64 = 200;
